name: Monthly Android Version 15 Docs Monitor

on:
  schedule:
   
    - cron: '0 0 1 * *'
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 markdownify

      - name: Run Python Script
        env:
          BASE_URLS: '["https://developer.android.com/about/versions/15"]'
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: python script.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          
          if git diff --staged --quiet; then
            echo "No changes in documentation to commit."
          else
            git commit -m "Automated update: Android Docs Snapshots $(date +'%Y-%m-%d')"
            git push
          fi
